swagger: "2.0"
info:
    title: Bank Argent API documentation
    description: Contains all available API endpoints in this codebase
    version: "1.0.0"
    termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
    - http
paths:
    /user/login:
        post:
            tags:
                - User Module
            summary: Login
            description: API for Login
            parameters:
                - in: body
                  name: body
                  description: Login Payload
                  required: true
                  schema:
                      $ref: "#/definitions/Login"
            produces:
                - application/json
            responses:
                "200":
                    description: Login Successfully
                    schema:
                        $ref: "#/definitions/LoginResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /user/signup:
        post:
            tags:
                - User Module
            summary: Signup
            description: API for Signup
            parameters:
                - in: body
                  name: body
                  description: Signup Payload
                  required: true
                  schema:
                      $ref: "#/definitions/User"
            produces:
                - application/json
            responses:
                "200":
                    description: Signup Successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /user/profile:
        post:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for fetching a user profile
            #produces:
            # - application/json
            responses:
                "200":
                    description: User profile retrieved successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for updating a user profile
            parameters:
                - in: body
                  name: body
                  description: Update user profile attributes
                  required: true
                  schema:
                      $ref: "#/definitions/UserProfile"
            produces:
                - application/json
            responses:
                "200":
                    description: User profile retrieved successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /account:
        post:
            tags:
                - Account Module
            summary: Accounts
            description: API for fetching user's account
            security:
                - Bearer[]
            responses:
                "200":
                    description: User's accounts retrieved successfully
                    schema:
                        $ref: "#/definitions/AccountResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
    /account/{accountID}/transactions:
        post:
            tags:
                - Account Module
            summary: Account transactions
            description: API for fetching transactions
            security:
                - Bearer[]
            parameters:
                - in: path
                  name: accountID
                  description: Account ID
                  required: true
                  type: string
            responses:
            "200":
                description: Transactions retrieved successfully
                schema:
                    $ref: "#/definitions/TransactionsResponse"
            "401": 
                description: Unauthorized
            "500": 
                description: Internal Server Error
    /account/{accountID}/transactions/{transactionID}/category:
        put:
            tags:
                - Account Module
            summary: Update Category
            description: API for update category
            security:
                - Bearer[]
            parameters:
                - in: path
                  name: accountID
                  description: Account ID
                  required: true
                  type: string
                - in: path
                  name: transactionID
                  description: Transaction ID
                  required: true
                  type: string
                - in: body
                  name: category
                  description: Update Category
                  required: true
                  type: string
            responses:
                "200":
                    description: Category modified successfully
                    schema:
                        $ref: "#/definitions/TransactionCategoryResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error

    /account/{accountID}/transactions/{transactionID}/note:
        post:
            tags:
                - Account Module
            summary: Add Note
            description: API for add note
            security:
                - Bearer[]
            parameters:
                - in: path
                  name: accountID
                  description: Account ID
                  required: true
                  type: string
                - in: path
                  name: transactionID
                  description: Transaction ID
                  required: true
                  type: string
                - in: body
                  name: note
                  description: Create note
                  required: true
                  type: string
            responses:
                "200":
                    description: Note created successfully
                    schema:
                        $ref: "#/definitions/TransactionNoteResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error

    /account/{accountID}/transactions/{transactionID}/note/{noteID}:
        put:
            tags:
                - Account Module
            summary: Update Note
            description: API for update note
            security:
                - Bearer[]
            parameters:
                - in: path
                  name: accountID
                  description: Account ID
                  required: true
                  type: string
                - in: path
                  name: transactionID
                  description: Transaction ID
                  required: true
                  type: string
                - in: path
                  name: noteID
                  description: Note ID
                  required: true
                  type: string
                - in: body
                  name: note
                  description: Update note
                  required: true
                  type: string
            responses:
                "200":
                    description: Note modified successfully
                    schema:
                        $ref: "#/definitions/TransactionNoteResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error

        delete:
            tags:
                - Account Module
            summary: Delete Note
            description: API for delete note
            security:
                - Bearer[]
            parameters:
                - in: path
                  name: accountID
                  description: Account ID
                  required: true
                  type: string
                - in: path
                  name: transactionID
                  description: Transaction ID
                  required: true
                  type: string
                - in: path
                  name: noteID
                  description: Note ID
                  required: true
                  type: string
                - in: body
                  name: note
                  description: delete note
                  required: true
                  type: string
            responses:
                "200":
                    description: Note deleted successfully
                    schema:
                        $ref: "#/definitions/TransactionNoteResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error

securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    User:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name
            userName:
                type: string
                description: user public name
    Login:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
    ApiResponse:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                    email:
                        type: string
    LoginResponse:
        type: object
        properties:
            token:
                type: string
    UserProfile:
        type: object
        properties:
            userName:
                type: string
    AccountResponse:
        type: object
        properties:
            accountID:
                type: string
            accountName:
                type: string
            accountCurrency:
                type: string
            currentBalance:
                type: number
                format: double
    TransactionsResponse:
        type: object
        properties:
            transactionID:
                type: string
            transactionType:
                type: string
            date:
                type: string
                format: date
            description:
                type: string
            amount:
                type: number
                format: double
            balance:
                type: number
                format: double
            category:
                type: string
            note:
                type: string
    TransactionCategoryResponse:
        type: object
        properties:
            category:
                type: string
    TransactionNoteResponse:
        type: object
        properties:
            note:
                type: string
            noteID:
                type: string
